Added JavaScript parser
swisnl/game-of-tests pull request #2
Opened 2018-02-02 16:29 UTC by JaZo

2018-02-02 21:07 UTC, bbrala commented
Thanks!

Added QUnit also since we are doing JS tests now :)

2018-02-02 21:07 UTC, bbrala approved these changes

2018-02-03 11:10 UTC, bbrala requested changes
Some things that need to be done still.

- [ ] Update readme of this repo, mention the Javascript parser.
- [ ] Update readme of [swisnl/game-of-tests-laravel](https://github.com/swisnl/game-of-tests-laravel).

2018-02-05 09:08 UTC, JaZo commented
I added more parsers and bundled the ones using the same syntax. This PR now includes:
- Ava
- Jasmine
- Jest
- Mocha
- Tape
- QUnit

PR for updated readme: swisnl/game-of-tests-laravel#3

2018-02-05 09:22 UTC, bbrala approved these changes

2018-02-05 09:59 UTC, merged